### ISSUE TITLE
Broken in ssr

### ISSUE THREAD

**Issue by javialon26** [marco-streng/styled-off-canvas#130]
I'm trying the component with Gatsby and I have an error in the SSR bundle:

WebpackError: ReferenceError: document is not defined

The problem is in Menu.js at line 27, maybe you can test document if not undefined.

Thanks

**Comment by javialon26** [comment]
Hi @marco-streng, it is working now. I tested with a production build of gatsby and with gatsby develop and everything was ok.

thank you!

**Comment by marco-streng** [comment]
Fixed in `v1.0.1`
